version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8000:8000"
    command: "yarn start"
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
